import { type ChangeEvent, useCallback, useEffect, useState } from "react";

type ApiStatus = "checking" | "connected" | "offline";
type NavItem = "Workspace" | "Library" | "Study tools" | "Analytics";
type StudyDocument = { id: string; original_name: string; file_type: string; size_bytes: number; page_or_slide_count: number | null; character_count: number; extraction_status: "ready" | "ocr_unavailable"; extraction_message: string | null; indexing_status: "not_indexed" | "indexed" | "no_text" | "indexing_error"; chunk_count: number; indexing_message: string | null; created_at: string; };

const navItems: { name: NavItem; icon: string }[] = [{ name: "Workspace", icon: "⌘" }, { name: "Library", icon: "▤" }, { name: "Study tools", icon: "✦" }, { name: "Analytics", icon: "◔" }];
const studyActions = [{ icon: "✦", title: "Ask your materials", text: "Start a source-grounded conversation." }, { icon: "☷", title: "Create study notes", text: "Turn readings into a clear structure." }, { icon: "▣", title: "Practice with a quiz", text: "Test understanding with generated questions." }, { icon: "◫", title: "Build flashcards", text: "Create rapid-review cards from concepts." }];

function App() {
  const [status, setStatus] = useState<ApiStatus>("checking");
  const [activeNav, setActiveNav] = useState<NavItem>("Workspace");
  const [isUploadOpen, setIsUploadOpen] = useState(false);
  const [documents, setDocuments] = useState<StudyDocument[]>([]);
  const [isIndexing, setIsIndexing] = useState(false);
  const [indexMessage, setIndexMessage] = useState<string | null>(null);
  const loadDocuments = useCallback(async () => { try { const response = await fetch("/api/v1/documents"); if (!response.ok) throw new Error(); const data: { documents: StudyDocument[] } = await response.json(); setDocuments(data.documents); } catch { /* API status is displayed separately. */ } }, []);

  useEffect(() => { const controller = new AbortController(); const checkBackend = async () => { try { const response = await fetch("/api/v1/health", { signal: controller.signal }); const data: { status?: string } = await response.json(); setStatus(response.ok && data.status === "ok" ? "connected" : "offline"); if (response.ok) void loadDocuments(); } catch { if (!controller.signal.aborted) setStatus("offline"); } }; void checkBackend(); return () => controller.abort(); }, [loadDocuments]);

  const statusLabel = status === "connected" ? "Local system ready" : status === "offline" ? "Backend unavailable" : "Connecting locally";
  const onUploaded = (document: StudyDocument) => { setDocuments((current) => [document, ...current]); setIsUploadOpen(false); setActiveNav("Library"); };
  const indexDocuments = async () => { setIsIndexing(true); setIndexMessage(null); try { const response = await fetch("/api/v1/documents/index", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const data: { message?: string; detail?: string } = await response.json(); if (!response.ok) throw new Error(data.detail ?? "Indexing could not finish."); setIndexMessage(data.message ?? "Knowledge base updated."); await loadDocuments(); } catch (error) { setIndexMessage(error instanceof Error ? error.message : "Indexing could not finish."); } finally { setIsIndexing(false); } };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span>✦</span></div><span>StudyMate <em>AI</em></span></div><div className="workspace-switcher"><span className="switcher-icon">◈</span><span>My workspace</span><span className="switcher-caret">⌄</span></div><nav aria-label="Main navigation"><p className="nav-label">WORKSPACE</p>{navItems.map((item) => <button className={`nav-item ${activeNav === item.name ? "active" : ""}`} key={item.name} onClick={() => setActiveNav(item.name)} type="button"><span className="nav-icon">{item.icon}</span>{item.name}{item.name === "Library" && documents.length > 0 && <b className="library-count">{documents.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="status-card"><span className={`status-light ${status}`}></span><div><strong>{statusLabel}</strong><small>Private • runs on this device</small></div></div><button className="help-link" type="button"><span>?</span> How StudyMate works</button><div className="profile"><div className="avatar">HS</div><div><strong>Hemanth Sai</strong><small>Local workspace</small></div><button type="button" aria-label="Account menu">•••</button></div></div></aside>
    <main className="main-content"><header className="topbar"><div className="crumb"><span>Workspace</span><b>/</b><strong>{activeNav}</strong></div><div className="topbar-actions"><button className="icon-button" type="button" aria-label="Notifications">♧</button><button className="avatar compact" type="button" aria-label="Profile">HS</button></div></header>{activeNav === "Library" ? <Library documents={documents} onUpload={() => setIsUploadOpen(true)} onIndex={() => void indexDocuments()} isIndexing={isIndexing} indexMessage={indexMessage} /> : <Workspace documents={documents} onUpload={() => setIsUploadOpen(true)} onOpenLibrary={() => setActiveNav("Library")} />}<footer><span>StudyMate AI</span><b>•</b> Your documents stay on this device <b>•</b><span className={`footer-dot ${status}`}></span> {status === "connected" ? "Backend connected" : status === "offline" ? "Start the backend to connect" : "Checking backend"}</footer></main>
    {isUploadOpen && <UploadDialog onClose={() => setIsUploadOpen(false)} onUploaded={onUploaded} />}
  </div>;
}

function Workspace({ documents, onUpload, onOpenLibrary }: { documents: StudyDocument[]; onUpload: () => void; onOpenLibrary: () => void }) {
  return <><section className="hero"><div className="eyebrow"><span></span> ADVANCED RAG LEARNING ASSISTANT</div><h1>Learn from <i>your</i> materials.</h1><p>Upload your course resources, then ask, explore, and study with answers grounded in your sources.</p><button className="primary-button" type="button" onClick={onUpload}><span>＋</span> Add learning materials</button><div className="supported"><span>Supported:</span> PDF <b>•</b> DOCX <b>•</b> PPTX <b>•</b> TXT <b>•</b> Images</div></section><section className="dashboard-grid"><div className="section-heading"><div><p className="eyebrow"><span></span> START EXPLORING</p><h2>What would you like to do?</h2></div><span className="phase-badge">Indexing arrives in Phase 3</span></div><div className="action-grid">{studyActions.map((action) => <button className="action-card" key={action.title} type="button" onClick={onUpload}><span className="card-icon">{action.icon}</span><span><strong>{action.title}</strong><small>{action.text}</small></span><span className="card-arrow">→</span></button>)}</div></section><section className="ready-section"><div className="section-heading"><div><p className="eyebrow"><span></span> YOUR KNOWLEDGE BASE</p><h2>{documents.length ? "Your local library" : "Ready when you are"}</h2></div><button className="text-button" type="button" onClick={documents.length ? onOpenLibrary : onUpload}>{documents.length ? "Open library" : "Add material"} <span>→</span></button></div>{documents.length ? <RecentDocuments documents={documents.slice(0, 3)} onOpenLibrary={onOpenLibrary} /> : <div className="empty-library"><div className="empty-icon">▤</div><div><h3>Your library is waiting</h3><p>Bring in your first study resource. StudyMate will extract its text locally and prepare it for semantic indexing in Phase 3.</p></div><button type="button" onClick={onUpload}>Upload a file</button></div>}</section></>;
}

function Library({ documents, onUpload, onIndex, isIndexing, indexMessage }: { documents: StudyDocument[]; onUpload: () => void; onIndex: () => void; isIndexing: boolean; indexMessage: string | null }) { return <section className="library-page"><div className="library-intro"><div><p className="eyebrow"><span></span> LOCAL DOCUMENT LIBRARY</p><h1>Your learning materials</h1><p>Files stay on this device. Create embeddings to make extracted material searchable by meaning.</p></div><div className="library-actions"><button className="secondary-button" disabled={!documents.length || isIndexing} onClick={onIndex} type="button">{isIndexing ? "Building knowledge base…" : "✦ Build knowledge base"}</button><button className="primary-button" onClick={onUpload} type="button"><span>＋</span> Upload material</button></div></div>{indexMessage && <p className="index-message">{indexMessage}</p>}{documents.length ? <DocumentTable documents={documents} /> : <div className="library-empty"><div className="empty-icon">▤</div><h2>No materials yet</h2><p>Upload PDFs, Word documents, PowerPoint slides, text files, or images to start your local study library.</p><button className="primary-button" type="button" onClick={onUpload}>Add your first material</button></div>}</section>; }
function RecentDocuments({ documents, onOpenLibrary }: { documents: StudyDocument[]; onOpenLibrary: () => void }) { return <div className="recent-documents">{documents.map((document) => <button className="recent-document" key={document.id} type="button" onClick={onOpenLibrary}><FileTypeIcon type={document.file_type} /><span><strong>{document.original_name}</strong><small>{formatDetails(document)}</small></span><span className={`document-state ${document.extraction_status}`}>{document.extraction_status === "ready" ? "Extracted" : "OCR needed"}</span></button>)}</div>; }
function DocumentTable({ documents }: { documents: StudyDocument[] }) { return <div className="document-table">{documents.map((document) => <article className="document-row" key={document.id}><FileTypeIcon type={document.file_type} /><div className="document-name"><strong>{document.original_name}</strong><small>{formatDetails(document)} • Added {new Date(document.created_at).toLocaleDateString()}</small>{document.extraction_message && <span className="document-note">{document.extraction_message}</span>}{document.indexing_message && <span className="document-note">{document.indexing_message}</span>}</div><div className="document-metric"><strong>{document.indexing_status === "indexed" ? document.chunk_count.toLocaleString() : document.character_count.toLocaleString()}</strong><small>{document.indexing_status === "indexed" ? "knowledge chunks" : "characters"}</small></div><span className={`document-state ${document.indexing_status}`}>{indexLabel(document)}</span></article>)}</div>; }
function FileTypeIcon({ type }: { type: string }) { return <span className={`file-icon ${type.toLowerCase()}`}>{type === "JPEG" ? "JPG" : type}</span>; }
function formatDetails(document: StudyDocument) { const location = document.page_or_slide_count ? `${document.page_or_slide_count} ${document.file_type === "PPTX" ? "slides" : "pages"}` : "Text document"; return `${location} • ${formatBytes(document.size_bytes)}`; }
function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
function indexLabel(document: StudyDocument) { if (document.indexing_status === "indexed") return "Search ready"; if (document.indexing_status === "no_text") return "No readable text"; if (document.indexing_status === "indexing_error") return "Indexing error"; return document.extraction_status === "ready" ? "Ready to index" : "OCR needed"; }

function UploadDialog({ onClose, onUploaded }: { onClose: () => void; onUploaded: (document: StudyDocument) => void }) {
  const [selectedFile, setSelectedFile] = useState<File | null>(null); const [isUploading, setIsUploading] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const onFileChange = (event: ChangeEvent<HTMLInputElement>) => { setSelectedFile(event.target.files?.[0] ?? null); setMessage(null); };
  const upload = async () => { if (!selectedFile) return; setIsUploading(true); setMessage(null); const form = new FormData(); form.append("file", selectedFile); try { const response = await fetch("/api/v1/documents/upload", { method: "POST", body: form }); const data: { document?: StudyDocument; detail?: string } = await response.json(); if (!response.ok || !data.document) throw new Error(data.detail ?? "Upload could not finish."); onUploaded(data.document); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload could not finish."); } finally { setIsUploading(false); } };
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal upload-modal" role="dialog" aria-modal="true" aria-labelledby="upload-title" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={onClose} aria-label="Close">×</button><div className="modal-icon">↑</div><p className="eyebrow"><span></span> LOCAL INGESTION</p><h2 id="upload-title">Add learning material</h2><p>StudyMate stores the original file locally and extracts its text. It does not send your material to a cloud service.</p><label className={`drop-zone file-picker ${selectedFile ? "has-file" : ""}`}><input type="file" accept=".pdf,.docx,.pptx,.txt,.png,.jpg,.jpeg,.webp" onChange={onFileChange} /><strong>{selectedFile ? selectedFile.name : "Choose a file"}</strong><small>{selectedFile ? formatBytes(selectedFile.size) : "PDF, DOCX, PPTX, TXT, PNG, JPG, or WEBP • max 50 MB"}</small></label>{message && <p className="upload-error">{message}</p>}<button className="upload-button" disabled={!selectedFile || isUploading} type="button" onClick={() => void upload()}>{isUploading ? "Extracting locally…" : "Upload and extract text"}</button></section></div>;
}
export default App;
